name: Node.js CI/CD Parallel & Sequential

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test

  deps-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm outdated || echo "All dependencies up-to-date"

  # --------------------
  # Sequential Jobs (after parallel jobs)
  # --------------------
  docker-build:
    runs-on: ubuntu-latest
    needs: [lint, test, deps-check]  # run only after parallel jobs succeed
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-parallel-ci:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build  # run only after Docker build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deployment step
      run: |
        echo "Deployment step: pull Docker image and run on server"
        # Example deployment commands:
        # docker pull ${{ secrets.DOCKERHUB_USERNAME }}/node-parallel-ci:latest
        # docker stop node-app || true
        # docker rm node-app || true
        # docker run -d -p 80:3000 --name node-app ${{ secrets.DOCKERHUB_USERNAME }}/node-parallel-ci:latest